[build]
  command = "pnpm --filter @workspace/spa-platform run build"
  publish = "web/dist"

[[redirects]]
  from = "/api/*"
  to = "https://spa-rouis-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
